export interface Event {
  id: string;
  title: string;
  artist: string;
  venue: string;
  city: string;
  date: string;
  dateLabel: string;
  dateTag: 'today' | 'tomorrow' | 'this-weekend' | 'this-month' | 'future';
  category: 'concerts' | 'sports' | 'theater' | 'comedy' | 'festivals';
  price: number;
  priceLabel: string;
  image: string;
  demand: number; // 0-100
  soldCount: number;
  totalCapacity: number;
  isSoldOut: boolean;
  isHot: boolean;
  tags: string[];
}

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'Midnight City Revival',
    artist: 'The Neon Collective',
    venue: 'Madison Square Garden',
    city: 'New York',
    date: '2026-04-22',
    dateLabel: 'Tomorrow · 8:00 PM',
    dateTag: 'tomorrow',
    category: 'concerts',
    price: 89,
    priceLabel: 'From $89',
    image: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 98,
    soldCount: 18200,
    totalCapacity: 20000,
    isSoldOut: false,
    isHot: true,
    tags: ['Rock', 'Indie', 'Live Band'],
  },
  {
    id: 'e2',
    title: 'The Chronicles World Tour',
    artist: 'VAUX',
    venue: 'The O2 Arena',
    city: 'London',
    date: '2026-05-03',
    dateLabel: 'May 3 · 7:30 PM',
    dateTag: 'this-month',
    category: 'concerts',
    price: 120,
    priceLabel: 'From $120',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 94,
    soldCount: 15900,
    totalCapacity: 17000,
    isSoldOut: false,
    isHot: true,
    tags: ['Pop', 'World Tour'],
  },
  {
    id: 'e3',
    title: 'NBA Finals — Game 5',
    artist: 'Lakers vs. Celtics',
    venue: 'Crypto.com Arena',
    city: 'Los Angeles',
    date: '2026-04-25',
    dateLabel: 'Apr 25 · 9:00 PM',
    dateTag: 'this-weekend',
    category: 'sports',
    price: 210,
    priceLabel: 'From $210',
    image: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 99,
    soldCount: 19800,
    totalCapacity: 20000,
    isSoldOut: false,
    isHot: true,
    tags: ['NBA', 'Basketball', 'Finals'],
  },
  {
    id: 'e4',
    title: 'Hamlet — Opening Night',
    artist: 'Royal Shakespeare Company',
    venue: 'Royal Albert Hall',
    city: 'London',
    date: '2026-05-10',
    dateLabel: 'May 10 · 7:00 PM',
    dateTag: 'this-month',
    category: 'theater',
    price: 65,
    priceLabel: 'From $65',
    image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 72,
    soldCount: 2100,
    totalCapacity: 3000,
    isSoldOut: false,
    isHot: false,
    tags: ['Shakespeare', 'Drama', 'Classic'],
  },
  {
    id: 'e5',
    title: 'Electronic Spring Festival',
    artist: 'Various Artists',
    venue: 'Coachella Valley',
    city: 'Indio',
    date: '2026-04-26',
    dateLabel: 'Apr 26-27 · All Day',
    dateTag: 'this-weekend',
    category: 'festivals',
    price: 350,
    priceLabel: 'From $350',
    image: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 97,
    soldCount: 94000,
    totalCapacity: 100000,
    isSoldOut: false,
    isHot: true,
    tags: ['EDM', 'Festival', 'Multi-day'],
  },
  {
    id: 'e6',
    title: 'Stand Up & Deliver',
    artist: 'Dave Chappelle',
    venue: 'Radio City Music Hall',
    city: 'New York',
    date: '2026-04-21',
    dateLabel: 'Tonight · 9:00 PM',
    dateTag: 'today',
    category: 'comedy',
    price: 95,
    priceLabel: 'From $95',
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 100,
    soldCount: 6000,
    totalCapacity: 6000,
    isSoldOut: true,
    isHot: true,
    tags: ['Comedy', 'Stand-up', 'Sold Out'],
  },
  {
    id: 'e7',
    title: 'Neon Pulse Tour',
    artist: 'AURORA',
    venue: 'Barclays Center',
    city: 'New York',
    date: '2026-06-01',
    dateLabel: 'Jun 1 · 8:00 PM',
    dateTag: 'future',
    category: 'concerts',
    price: 75,
    priceLabel: 'From $75',
    image: 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 81,
    soldCount: 9200,
    totalCapacity: 16000,
    isSoldOut: false,
    isHot: false,
    tags: ['Electronic', 'Synth-pop'],
  },
  {
    id: 'e8',
    title: 'Super Liga Final',
    artist: 'Barcelona vs Real Madrid',
    venue: 'Camp Nou',
    city: 'Barcelona',
    date: '2026-05-15',
    dateLabel: 'May 15 · 8:45 PM',
    dateTag: 'this-month',
    category: 'sports',
    price: 180,
    priceLabel: 'From $180',
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 96,
    soldCount: 97000,
    totalCapacity: 99000,
    isSoldOut: false,
    isHot: true,
    tags: ['Football', 'La Liga', 'El Clasico'],
  },
  {
    id: 'e9',
    title: 'Jazz Under the Stars',
    artist: 'Miles & The Quartet',
    venue: 'Hollywood Bowl',
    city: 'Los Angeles',
    date: '2026-05-20',
    dateLabel: 'May 20 · 7:30 PM',
    dateTag: 'this-month',
    category: 'concerts',
    price: 45,
    priceLabel: 'From $45',
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 60,
    soldCount: 8100,
    totalCapacity: 17500,
    isSoldOut: false,
    isHot: false,
    tags: ['Jazz', 'Outdoor', 'Summer'],
  },
  {
    id: 'e10',
    title: 'The Phantom of the Opera',
    artist: 'Broadway Cast',
    venue: 'Majestic Theatre',
    city: 'New York',
    date: '2026-04-24',
    dateLabel: 'Apr 24 · 7:30 PM',
    dateTag: 'this-weekend',
    category: 'theater',
    price: 115,
    priceLabel: 'From $115',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 85,
    soldCount: 1700,
    totalCapacity: 1800,
    isSoldOut: false,
    isHot: true,
    tags: ['Musical', 'Broadway', 'Classic'],
  },
  {
    id: 'e11',
    title: 'Ultra Music Festival',
    artist: 'Tiësto · Martin Garrix · More',
    venue: 'Bayfront Park',
    city: 'Miami',
    date: '2026-06-15',
    dateLabel: 'Jun 15-17 · 3 Days',
    dateTag: 'future',
    category: 'festivals',
    price: 420,
    priceLabel: 'From $420',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 91,
    soldCount: 62000,
    totalCapacity: 75000,
    isSoldOut: false,
    isHot: true,
    tags: ['EDM', 'Festival', '3-Day Pass'],
  },
  {
    id: 'e12',
    title: 'Wicked — 25th Anniversary',
    artist: 'West End Cast',
    venue: 'Apollo Victoria Theatre',
    city: 'London',
    date: '2026-05-05',
    dateLabel: 'May 5 · 7:30 PM',
    dateTag: 'this-month',
    category: 'theater',
    price: 88,
    priceLabel: 'From $88',
    image: 'https://images.unsplash.com/photo-1596003906949-67221c37965c?auto=format&fit=crop&q=80&w=800&h=500',
    demand: 79,
    soldCount: 2400,
    totalCapacity: 2500,
    isSoldOut: false,
    isHot: false,
    tags: ['Musical', 'West End', 'Anniversary'],
  },
];